-- Ejecuta este código en el SQL Editor de Supabase

-- 1. Tabla para la Bandeja de Mensajes (Formulario de Contacto)
CREATE TABLE IF NOT EXISTS public.mensajes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  mensaje text,
  leido boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabla para los Puntos del Mapa Dinámico
CREATE TABLE IF NOT EXISTS public.mapa_puntos (
  id bigint generated by default as identity primary key,
  lat numeric not null,
  lng numeric not null,
  titulo text not null,
  texto text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Habilitar permisos públicos (lectura y escritura para simplificar la integración del sitio estático sin tokens complejos)
ALTER TABLE public.mensajes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mapa_puntos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserción pública de mensajes" 
ON public.mensajes FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir lectura y gestión a todo el mundo de mensajes" 
ON public.mensajes FOR ALL USING (true);

CREATE POLICY "Permitir lectura y gestión a todo el mundo del mapa" 
ON public.mapa_puntos FOR ALL USING (true);

-- 4. Insertar datos por defecto para el mapa (Opcional, pero recomendado para no perder los que ya tenías)
INSERT INTO public.mapa_puntos (lat, lng, titulo, texto) VALUES
(0.592, -77.831, 'SAN GABRIEL', 'Compromiso: Recuperación total del Casco Colonial y Seguridad Comercial.'),
(0.612, -77.745, 'CRISTÓBAL COLÓN', 'Compromiso: Fortalecimiento de la tecnificación del cultivo de papa.'),
(0.505, -77.865, 'LA PAZ', 'Compromiso: Potencialización turística de la Gruta y vialidad rural.'),
(0.635, -77.880, 'PIARTAL', 'Compromiso: Sistema de riego comunitario y apoyo al sector lechero.'),
(0.665, -77.820, 'FERNÁNDEZ SALVADOR', 'Compromiso: Atención médica móvil y maquinaria permanente para el campo.'),
(0.575, -77.885, 'CHITÁN DE NAVARRETE', 'Compromiso: Infraestructura deportiva y fomento al emprendimiento juvenil.');
